name: fitness_domain
description: Fitness domains

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.1
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1
  firebase_storage: ^11.4.0
  tuple: ^2.0.0
  file_picker: ^6.0.0
  json_annotation: ^4.0.1
  loading_animations: ^2.2.0
  get: ^4.3.8
  get_it: ^7.6.4
  provider: ^6.0.5
  http: ^1.1.0
  firebase:
    path: ../firebase
dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^6.7.1
  lint: ^2.1.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
