name: firebase
description: Firebase package

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1
  firebase_storage: ^11.4.0
  animations: ^2.0.1
  get: ^4.3.8

#
#  cupertino_icons: ^1.0.3
#  rxdart: ^0.27.1
#  provider: ^5.0.0

#  google_sign_in: ^5.0.4
#  google_fonts: ^2.1.0
#  tuple: ^2.0.0
#  json_annotation: ^4.0.1
#  file_picker: ^3.0.3
#  http: ^0.13.3
#  path: ^1.8.0
#  fluttertoast: ^8.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
